language: java

sudo: false

jdk: oraclejdk8

install:
  - mvn install -DskipTests -Dmaven.javadoc.skip -Dcheckstyle.skip -B -V

script:
  - mvn test # unit tests
  - mvn -Dcheckstyle.skip verify # integration tests (repeats unit tests)
  - mvn checkstyle:check # check style

after_success:
  - mvn coveralls:report # report test coverage (will only succeed in integration test mode)
